### ISSUE TITLE
Set Up Django Basic Backend

### ISSUE THREAD

**Issue by Brgraul** [Brgraul/START-Hack#2]

**Comment by Arc676** [comment]
Required method:
- [ ] `get_emotion_threshold` returns the minimum value for an emotion in Azure's JSON response to be considered relevant
- [ ] `get_emotion_change_threshold` returns the minimum alteration in emotion required to trigger providing feedback (as represented as a 2-norm in R^8)
- [ ] `get_delta_threshold` returns the minimum absolute alteration in the value of an emotion for this change to be relevant for feedback
